# Generated by Django 4.0.4 on 2022-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/img/blog_images'),
        ),
    ]
